In [1]:
import requests
import urllib.request
import time
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
from urllib.request import urlopen
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
html = urlopen(url) 
soup = BeautifulSoup(html, 'html.parser')
My_table = soup.find('table',{'class':'wikitable sortable jquery-tablesorter'})
soup = soup.find_all("table")
Postal_Code = []
Borough = []
Neighbourhood = []
#print(soup)

In [2]:
Post = []
Bor = []
Neig = []
for table in soup:
    #print(table)
    if len(table) >1:
    #if class="wikitable sortable jquery-tablesorter"
        rows = table.find_all('tr')
        for row in rows:
            cells = row.find_all('td')
            #print(cells)
        
        
            if len(cells) == 3:
                Postal_Code = cells[0]
                p=Postal_Code.get_text().strip()
                Post.append(p)
                
                Borough = cells[1]
                b=Borough.get_text().strip()
                Bor.append(b)
            
                Neighbourhood = cells[2]
                n=Neighbourhood.get_text().strip()
                Neig.append(n)   
                
#df1 = pd.DataFrame(index=[Post],[Bor],[Neig])
df2 = pd.DataFrame(list(zip(Post, Bor, Neig)),columns=['a', 'b', 'c'])
df2

       a                 b                                                  c
0    M1A      Not assigned                                       Not assigned
1    M2A      Not assigned                                       Not assigned
2    M3A        North York                                          Parkwoods
3    M4A        North York                                   Victoria Village
4    M5A  Downtown Toronto                          Regent Park, Harbourfront
..   ...               ...                                                ...
175  M5Z      Not assigned                                       Not assigned
176  M6Z      Not assigned                                       Not assigned
177  M7Z      Not assigned                                       Not assigned
178  M8Z         Etobicoke  Mimico NW, The Queensway West, South of Bloor,...
179  M9Z      Not assigned                                       Not assigned

[180 rows x 3 columns]